### ISSUE TITLE
Weird results when processing frame by frame

### ISSUE THREAD

**Issue by phucsilverai** [shangwei5/ST-AVSR#4]
Hi,

Thank you for the great work! 

I tried running your code on my videos, but the results were unexpected. Specifically, I used `test.sh` (process frame by frame) to upscale the video by 4x (expecting from 960 x 540 to 3840 x 2160), but the resulting video remained the same dimension, and the quality was even worse. Please see the attached input and output for reference. Do you have any ideas on what might be causing this issue?

Many thanks.

Here's the input and output videos: https://drive.google.com/drive/folders/1PZHSIzuj6k7YN4q93XlVr3oRWjQH2Gdv?usp=sharing 

Here's the code to run
```bash
CUDA_VISIBLE_DEVICES=0 python test.py   --data_path  './test_data/input4x' --result_path './test_data/output4x' --space_scale  "4,4"
```

Here's the code I used to extract frames from all the videos in a directory.
```python
import os
import imageio

def extract_frames_from_videos(input_path, output_path):
    # Ensure the output path exists
    if not os.path.exists(output_path):
        os.makedirs(output_path)

    # Get list of all video files in the input path
    video_files = [f for f in os.listdir(input_path) if os.path.isfile(os.path.join(input_path, f))]

    for video_file in video_files:
        video_name, _ = os.path.splitext(video_file)
        video_output_path = os.path.join(output_path, video_name)

        # Create a directory for the video frames
        if not os.path.exists(video_output_path):
            os.makedirs(video_output_path)

        # Read the video
        video_reader = imageio.get_reader(os.path.join(input_path, video_file))

        # Extract and save frames
        for i, frame in enumerate(video_reader):
            frame_path = os.path.join(video_output_path, f"frame_{i:04d}.png")
            imageio.imwrite(frame_path, frame)
```

**Comment by shangwei5** [comment]
If you want to test on your own video, you need to remove the part that downsamples the input from [Line110](https://github.com/shangwei5/ST-AVSR/blob/f25ee22ed54b13f1ac781345b5d218678e927547/test_sequence.py#L110) to [Line115](https://github.com/shangwei5/ST-AVSR/blob/f25ee22ed54b13f1ac781345b5d218678e927547/test_sequence.py#L115). 
Our model is trained on REDS using Bicubic downsampling, and if the input video contains more complex degradation, the results may also be affected. You can add real video degradation to our model for fine-tuning.

**Comment by phucsilverai** [comment]
Thank you for your response. When I removed the part from Line 110 to 115, the results were clearer, but the dimensions were still not upsampled and remained the same. I tried several other approaches, including upsampling the image first before processing it, and I was able to run it with scale_factor = "3,3" on one A100 . However, with scale_factor = "4,4", it resulted in a CUDA OOM error. Do you have any suggestions on how to overcome this issue?

For that approach, I added this line after [line 101](https://github.com/shangwei5/ST-AVSR/blob/f25ee22ed54b13f1ac781345b5d218678e927547/test_sequence.py#L101C17-L101C67)
`inputs = [cv2.resize(img, (int(img.shape[1] * 1/scale_w[0].item()), int(img.shape[0] * 1/scale_h[0].item())), interpolation=cv2.INTER_CUBIC) for img in inputs]`

**Comment by shangwei5** [comment]
Oh, you should also change `hr_coord`, which affects the target size and position of the target. I just made adjustments to the test code, but I didn't have time to debug it. Let's see if this can solve your problem. [test_seq_yours.py](https://github.com/shangwei5/ST-AVSR/blob/b07bcd7fe50b92129fb8d3c4ccd71c2fc44235e2/test_seq_yours.py).
Regarding OOM, since the resolution of your input video is relatively high, if there is not enough GPU memory, you can perform local SR by cropping the `hr_coord` and feeding them into the model separately to output the super-resolution results for the corresponding region.

**Comment by shangwei5** [comment]
We have updated the code, and using [test_seq_yours.py](https://github.com/shangwei5/ST-AVSR/blob/b07bcd7fe50b92129fb8d3c4ccd71c2fc44235e2/test_seq_yours.py) may solve your problem. The OOM issue has been alleviated by slicing. If you find it helpful, please give me a star.

**Comment by phucsilverai** [comment]
Thank you for your support. I tested the new code and found that it worked well with your sample videos. However, when I tested it with my video (960 x 540), it still encountered an OOM issue on a T4, even across a wide range of `--max_patch` values from 16 to 1024. 
Nevertheless, this is excellent work, and I've given it a star ⭐️.
